name: Build Yolov8NCNN AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install newer CMake
        run: sdkmanager "cmake;3.22.1"

      - name: Write local.properties
        run: echo "cmake.dir=$ANDROID_HOME/cmake/3.22.1" > local.properties

      - name: Grant Permission
        run: chmod +x ./gradlew

      - name: Build AAR
        run: |
          ./gradlew clean
          ./gradlew assembleRelease --warning-mode all

      - name: Upload AAR
        uses: actions/upload-artifact@v4.3.1
        with:
          name: yolov8ncnn-aar
          path: app/build/outputs/aar/*.aar
